### ISSUE TITLE
音量

### ISSUE THREAD

**Issue by JackyZhaoG** [woxieao/-1s#1]
请问如何配置音量

**Comment by woxieao** [comment]
右键图标 点EditConfig,第一行的数字改大点然后保存后重启即可
![image](https://user-images.githubusercontent.com/11471341/86234821-164aa500-bbca-11ea-866c-6ce3053762be.png)

**Comment by dongzhuoer** [comment]
第一行是频率吧。这个好像只能跟随系统音量设置了。
