### ISSUE TITLE
工作列CPU溫度的顏色修改 & ALT+TAB是否可隱藏應用程式

### ISSUE THREAD

**Issue by imgonewild** [woxieao/-1s#10]
1. 希望可以增加 設定溫度顏色的功能
因為我是用dark toolbar 所以黑底藍字會看不清楚

2. ALT+TAB會出現應用程式(視窗內有Test按鈕)
希望可以不顯示 謝謝

謝謝
另外40Hz用起來很順暢

**Comment by woxieao** [comment]
已新增主题色&alt+tab不会再显示了
