### ISSUE TITLE
文本显示

### ISSUE THREAD

**Issue by 2thcmoon** [woxieao/-1s#11]
![image](https://user-images.githubusercontent.com/56881023/141283221-b62466e7-bd1b-4905-b098-8b276ea36d45.png)
CPU写成了CUP hahaha

**Comment by woxieao** [comment]
少年好眼力..下次有大动作再改过来算了..

**Comment by woxieao** [comment]
> ![image](https://user-images.githubusercontent.com/56881023/141283221-b62466e7-bd1b-4905-b098-8b276ea36d45.png) CPU写成了CUP hahaha

少侠好眼力..下次有大动作再改过来算了..

**Comment by cxfy** [comment]
> > ![image](https://user-images.githubusercontent.com/56881023/141283221-b62466e7-bd1b-4905-b098-8b276ea36d45.png) CPU写成了CUP hahaha
> 
> 少侠好眼力..下次有大动作再改过来算了..

刚为这个蓝牙音箱的断联烦恼，就看到了你的回答，感谢你开发的作品，太好用了！

**Comment by woxieao** [comment]
> > > ![image](https://user-images.githubusercontent.com/56881023/141283221-b62466e7-bd1b-4905-b098-8b276ea36d45.png) CPU写成了CUP hahaha
> > 
> > 
> > 少侠好眼力..下次有大动作再改过来算了..
> 
> 刚为这个蓝牙音箱的断联烦恼，就看到了你的回答，感谢你开发的作品，太好用了！

哈哈,客气

**Comment by woxieao** [comment]
已修复
