### ISSUE TITLE
是否可以支持设置更长的哔哔间隔时间

### ISSUE THREAD

**Issue by xtthaop** [woxieao/-1s#14]
任务栏那里是否可以支持自定义间隔时间

**Comment by xtthaop** [comment]
用 Visual Studio 自己生成了一个 9 分钟间隔的 爽 感谢作者分享！！！

**Comment by xtthaop** [comment]
> > 用 Visual Studio 自己生成了一个 9 分钟间隔的 爽 感谢作者分享！！！
> 
> 能分享下吗，我也感觉间隔时间太短了

可以啊

**Comment by masquevil** [comment]
@xtthaop 同求一个！

**Comment by eoirwt** [comment]
> 用 Visual Studio 自己生成了一个 9 分钟间隔的 爽 感谢作者分享！！！

能分享以下您改进后的软件吗？或者您能出个教程吗？

**Comment by xtthaop** [comment]
> > 用 Visual Studio 自己生成了一个 9 分钟间隔的 爽 感谢作者分享！！！
> 
> 能分享以下您改进后的软件吗？或者您能出个教程吗？

你要急的话先用这个 9 分钟的
链接：https://pan.baidu.com/s/13Nj70TqDIY_82Vf5MwoTZw?pwd=wxbx 
提取码：wxbx

**Comment by woxieao** [comment]
已新增自定义配置时间的功能
