### ISSUE TITLE
CPU温度很实用，但是，我说但是了啊，温度很不准

### ISSUE THREAD

**Issue by Laidezhong** [woxieao/-1s#7]
我是thinkpad x13 锐龙版，4750u 的 cpu，用多个软件测试温度在70度左右，但咋们这个软件一直在100度以上。

**Comment by woxieao** [comment]
> 我是thinkpad x13 锐龙版，4750u 的 cpu，用多个软件测试温度在70度左右，但咋们这个软件一直在100度以上。

你可以下载代码..整个编译后温度显示-30的程序..
